version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:8
  working_directory: ~/project/npmnow

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

install_steps: &install_steps
  steps:
    - checkout
    - *attach_workspace
    - restore_cache:
        name: Restore node_modules cache
        keys:
          - node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-modules-{{ .Branch }}-
          - node-modules-
    - run:
        name: Install Dependencies
        command: npm i
    - save_cache:
        name: Save node_modules cache
        key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - node_modules/
    - persist_to_workspace:
        root: ~/project
        paths: npmnow

test_steps: &test_steps
  steps:
    - checkout
    - restore_cache:
        key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run:
        name: Install Local Packages
        command: npm i
    - run:
        name: Test Suite
        command: npm run test

jobs:
  install:
    <<: *docker_defaults
    <<: *install_steps

  audit:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: NPM Audit Fix
          command: npm audit fix

  eslint:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: ESLint
          command: npm run eslint

  test-node-8:
    <<: *docker_defaults
    <<: *test_steps

  test-node-10:
    working_directory: ~/jest-express
    docker:
      - image: circleci/node:10
    <<: *test_steps

  test-node-11:
    working_directory: ~/jest-express
    docker:
      - image: circleci/node:11
    <<: *test_steps

  now:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - run:
          name: Deploy to Now
          command: now --token $ZEIT_TOKEN && now --token $ZEIT_TOKEN alias

workflows:
  version: 2
  install-test-build-and-publish:
    jobs:
      - install
      - audit:
          requires:
            - install
      - eslint:
          requires:
            - audit
      - test-node-8:
          requires:
            - eslint
      - test-node-10:
          requires:
            - eslint
      - test-node-11:
          requires:
            - eslint
      - now:
          requires:
            - test-node-8
            - test-node-10
            - test-node-11
